// <auto-generated />
namespace TrainReservation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201610062217019_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201610062217019_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201610301809064_201610062217019_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
